#!/bin/bash
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Spaghetti Bolognese", "price": 12.99}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Margherita Pizza", "price": 9.99}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Caesar Salad", "price": 7.99}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Chicken Alfredo", "price": 14.50}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Lasagna", "price": 13.99}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Grilled Salmon", "price": 18.50}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Ribeye Steak", "price": 24.99}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Chicken Caesar Wrap", "price": 10.50}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Garlic Bread", "price": 4.99}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Tiramisu", "price": 5.99}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Cheesecake", "price": 6.50}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Chocolate Brownie", "price": 4.50}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Apple Pie", "price": 5.50}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Coca-Cola", "price": 2.50}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Orange Juice", "price": 3.50}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Espresso", "price": 2.00}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Cappuccino", "price": 3.00}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Iced Tea", "price": 2.75}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Water", "price": 1.50}'
curl -X POST http://localhost:8084/plates -H "Content-Type: application/json" -d '{"description": "Lemonade", "price": 2.99}'
